server {
    # HTTP 요청이 들어오면 
    listen 80;
    server_name moodbook.live www.moodbook.live;
    location / {
        # 모든 요청을 HTTPS로 리디렉션 
        return 301 https://$host$request_uri;
    }
}

server {
    # 443 포트에서 SSL(HTTPS) 요청을 처리
    listen 443 ssl;
    server_name moodbook.live www.moodbook.live;

    # SSL 인증서 경로 설정
    ssl_certificate /etc/ssl/certs/fullchain.pem;
    ssl_certificate /etc/ssl/certs/privkey.pem;

    # SSL 설정
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers HIGH:!aNULL:!MD5;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}