server {
    # HTTP 요청이 들어오면 
    listen 80;
    server_name moodbook.live www.moodbook.live;
    location / {
        # 모든 요청을 HTTPS로 리디렉션 
        return 301 https://$host$request_uri;
    }
}

server {
    # 443 포트에서 SSL(HTTPS) 요청을 처리
    listen 443 ssl;
    server_name moodbook.live www.moodbook.live;

    # SSL 인증서 경로 설정
    ssl_certificate /etc/ssl/certs/fullchain.pem;
    ssl_certificate /etc/ssl/certs/privkey.pem;

    # SSL 설정
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers HIGH:!aNULL:!MD5;

    root /usr/share/nginx/html;
    index index.html;

    location /api {
        proxy_pass http://43.200.89.83:8080;
        proxy_set_header Connection 'keep-alive';
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        client_max_body_size 100M;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}