name: FRONT-WORKFLOW
on:
  push:
    branches: [ "dev" ]
jobs:
  front-job:
    runs-on: ubuntu-latest
    steps:
      - name: SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            set -e
            echo "SSH 접속 완료"

            cd /home/ubuntu

            if [ ! -d "moodbook-frontend/.git" ]; then
              echo "📂 moodbook-frontend 디렉토리 없음. 클론 시작..."
              git clone -b dev https://github.com/moodbook-space/moodbook-frontend.git moodbook-frontend
            else
              echo "📂 moodbook-frontend 디렉토리 존재. Pull로 최신화..."
              cd moodbook-frontend
              git reset --hard
              git clean -fd
              git pull origin dev
            fi

            cd moodbook-frontend

            echo "환경 설정 파일 생성"
            echo -e "VITE_REST_SERVER=${{ secrets.REST_SERVER }}" >> .env

            echo "🐳 Docker Compose로 빌드 및 배포 시작"
            docker compose up -d --build

      - name: 디스코드 성공 알림 전송
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content":"🚀 `FRONTEND : ${{ github.ref_name }}`에 빌드 성공, EC2에 배포 완료!"}' \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
               
      - name: 디스코드 실패 알림 전송
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content":"🚀 `FRONTEND : ${{ github.ref_name }}` 빌드 실패. 로그 확인 필요."}' \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
